from build_graph import *
import random


def projective_points(F, g):
    """
    Generate all points of P^(2^g - 1)(F).

    Returns canonical projective representatives as tuples.
    """

    N = 2**g

    P = ProjectiveSpace(F, N - 1)

    for pt in P.rational_points():
        yield tuple(pt)



def BFS(start_theta, only_isogs=False, max_depth=None, V_real = []):
    """
    Traverse the graph generated by radical_step.


    Parameters
    ----------
    start_theta:
        Initial theta point

    only_isogs:
        Build the isogeny graph

    max_depth:
        Optional BFS depth cutoff

    V_real:
        List of vertices in the actual isogeny graph

    Returns
    -------

    Vertices:
        normalized projective theta points

    counterfits_really:
        Solutions to problem 2

    counterfits_almost:
        Pseudo-paths between non-isogenous abelian varieties
    """

    start = normalize_tuple(start_theta)

    vertices = {start}
    edges = defaultdict(set)

    q = deque([(start, 0)])
    visited = {start}

    parent = {start: None}

    ctr_loops = 0

    counterfits_really = []
    counterfits_almost = []
    while q:
        ctr_loops += 1
        if ctr_loops % 1000 == 0:
            print(f"size of queue: {len(q)}")
            print(f"size of V = {len(vertices)}")
        theta, depth = q.popleft()

        if max_depth is not None and depth >= max_depth:
            continue

        nbrs = radical_step_normalized(theta, only_isogs = only_isogs)

        theta_is_variety = check_riemann(theta)

        # Dead end allowed naturally if nbrs == empty set
        for tt in nbrs:
            if (not theta_is_variety) and check_riemann(tt):
                print("COUNTERFIT PATH MAYBE FOUND!!")
                path = [tt]
                cur = theta
                while cur is not None:
                    path.append(cur)
                    cur = parent[cur]
                if tt in V_real:
                    print("WOW ACTUAL COUNTERFIT PATH")
                    counterfits_really.append(path[::-1])
                else:
                    print("nvm, not isogenous...")
                    counterfits_almost.append(path[::-1])
            # Add edge theta -> tt
            edges[theta].add(tt)

            if tt not in vertices:
                vertices.add(tt)

            if tt not in visited:
                parent[tt] = theta

                visited.add(tt)
                q.append((tt, depth + 1))

    return vertices, counterfits_really, counterfits_almost

import os
import pickle

def load_or_build_isogeny_graph(theta0, p):
    filename = f"graph_p{p}.pkl"

    if os.path.exists(filename):

        print(f"Loading cached graph from {filename}...")

        with open(filename, "rb") as f:
            V = pickle.load(f)

        return V

    print(f"Building full graph for p = {p}...")

    V, _, _ = BFS(theta0, only_isogs=True)
    print(f"Done! Graph has {len(V)} vertices")
    assert len(V) > 10

    print(f"Saving graph to {filename}...")

    with open(filename, "wb") as f:
        pickle.dump(V, f)

    return V

if __name__=="__main__":
    #p = 3
    #p = 7
    p = 103
    Fp2 = GF(p**2, name="i", modulus=[1, 0, 1])
    E0 = EllipticCurve(Fp2, [1, 0])
    assert E0.is_supersingular()

    theta0 = curve_to_theta_3(E0, E0, E0)

    if p > 100:
        V = []
    else:
        V = load_or_build_isogeny_graph(theta0, p)

    print("looking for counterfit path...")
    vertices, counterfits_really, counterfits_almost = BFS(theta0, V_real = V)

    print(f"solutions to prob 2: {len(counterfits_really)}")
    print(f"Fake solutions to prob 2: {len(counterfits_almost)}")


    random.shuffle(counterfits_really)
    for path in counterfits_really[:10]:
        print("--- new path ---")
        for tt in path:
            print(f"theta0 = {tt}. ab var? {check_riemann(tt)}")

    print("\n\n")
    endings = [p[-1] for p in counterfits_really]
    endings = list(set(endings))
    print(f"number of unique ending for pseudopaths: {len(endings)}")
    for tt in endings[:10]:
        print(tt)


    #ctr = 0
    #for x in projective_points(Fp2, 3):
    #    if ctr % 100 == 0:
    #        print(ctr)
    #    if check_riemann(x):
    #        continue
    #    RR, depth = BFS(x)
    #    if RR:
    #        print(f"x = {x} led to a path (depth = {depth})!!")





